name: gpxpr lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unittest-coverage:
    name: Run code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.8 for unitttests.
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Run linting tools
        run: |
            make install-dev
            make lint
